# Generated by Django 3.2.4 on 2021-06-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=32, null=True, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
